### ISSUE TITLE
Change invoice prefix in the file name

### ISSUE THREAD

**Issue by gelnior** [guyzmo/clait#3]
Is it possible to change the invoice prefix in the file name? Currently it's `IV`, I would like to change it to `FA`.

**Comment by guyzmo** [comment]
it is not, but it can be made configurable, there's only two places where it's being used

**Comment by guyzmo** [comment]
just add the following in `invoices_config.yaml`:

```yaml
prefix:
    invoice: FA
    quote: DV
```

😉
